name: castify
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  get_it: ^7.6.4
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  persian_tools: ^1.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 700

    - family: MR
      fonts:
        - asset: fonts/mh.ttf
          weight: 700

